(test test-sexpr-tests
   (assert-true (sexpr-bool? (SexprBool #t)))
   (assert-false (sexpr-bool? (SexprInt 5)))
   (assert-true (sexpr-char? (SexprChar #\A)))
   (assert-false (sexpr-char? (SexprInt 5)))
   (assert-true (sexpr-double? (SexprDouble 3.14)))
   (assert-false (sexpr-double? (SexprInt 5)))
   (assert-true (sexpr-int? (SexprInt 5)))
   (assert-false (sexpr-int? (SexprString "foo")))
   (assert-true (sexpr-list? (SexprList (Nil))))
   (assert-false (sexpr-list? (SexprString "foo")))
   (assert-true (sexpr-string? (SexprString "foo")))
   (assert-false (sexpr-string? (SexprInt 5)))
   (assert-true (sexpr-symbol? `foo))
   (assert-false (sexpr-symbol? (SexprInt 5))))
