#!/bin/bash
uname -a | grep Darwin > /dev/null
if [ $? -eq 0 ]; then
BASEDIR=$(dirname $0)
else
BASEDIR=$(dirname $(readlink -f "$0"))
fi
RLWRAP=`which rlwrap 2> /dev/null`
if [ $? -eq 0 ]; then
$RLWRAP java -jar $BASEDIR/scheml.jar $*
else
java -jar $BASEDIR/scheml.jar $*
fi
